name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd webapp
          pip install -r requirements.txt

      - name: Build Docker Image
        run: |
          docker build -t webapp:${{ github.sha }} ./webapp

  deploy-staging:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy to Staging
        run: echo "Uygulama Staging ortamına başarıyla gönderildi!"
